### ISSUE TITLE
Thoughts on adding page-sections? 

### ISSUE THREAD

**Issue by tk8817** [p0deje/watirsome#9]
hey @p0deje, 

My team has been looking at moving away from the page-object gem and backing a leaner watir only solution which believes in extensibility. We really like what you are doing with watirsome and would love to know if you have any intention of adopting the concept of page-sections.

If it is something you would be interested in coding or having accepted via a PR, then we would love to migrate to watirsome. We don't like the idea of living on a lonely fork of our own, haha.

**Comment by p0deje** [comment]
hey @tk8817 

Page sections (or regions in watirsome) is something that can definitely be improved. Current mechanism based on modules and mixins is definitely not the best and my team already struggles with the problems it brings (like method names collisions when dozens of regions are included in single page class).

At the same time, I still don't have a clear picture of how it should work. The only idea I have for now is something like this:

```ruby
class PostsRegion
  include Watirsome::Region

  def open_post(post_title)
    # code to open post
  end
end

class Page
  region :posts
end

page = Page.new(browser)
page.posts.open_post('watirsome')
```

This means that each region is a class and can be reached by convention accessor (`FooRegion => Page#foo`). I see both advantages (no name collision, easier to follow which method from which region is used) and disadvantages (not so easy to implement polymorphism as it is now) of this approach.

With that said, it would be great if you could show me how this works in your team and what's your API details. If we can settle on some specific interface details, I'll be happy to implement (though not sure when I'll have time) or merge a PR.

**Comment by tk8817** [comment]
Thanks for the detailed reply, sounds like we can find a path to success here. My team the @automation-wizards are going to have a think on it and put together a PR proposal. 

Best,
J

**Comment by p0deje** [comment]
I also would like to hear what @sh3pik and @nonkor think about that.

**Comment by sh3pik** [comment]
Nothing to say 😄 I like the idea! if it's possible to initialize regions only when they are needed (when `PostsRegion#open_post` is called), it'd be even better.

**Comment by nonkor** [comment]
@p0deje I always was a supporter of an idea to manage objects from a region in a separate namespace. So I vote for it definitely! And I like that syntax which you briefly described.

Just one suggestion (but sure about its utility).
I guess it would be nice to have a way to create a small region for certain page without including a separate file.
Like, 
```ruby

class Page
  include Watirsome::Page

  region :posts, class: 'post' do
    div :title, class: title
  end
end

page = Page.new(browser)
puts page.posts.title # or puts page.posts.title_div.text
```
But as I said not sure it worth it. In that case, we cannot define region methods inside, only for page namespace.

**Comment by p0deje** [comment]
> I guess it would be nice to have a way to create a small region for certain page without including a separate file.

Makes sense to me.

Looking forward to hear from @tk8817.

**Comment by nonkor** [comment]
@p0deje @tk8817 
One more idea which could be useful. I believe in region description we have to define global locator for the region, to simplify construction locators of elements inside. So, instead of 
```ruby
class PostsRegion
  include Watirsome::Region

  div :title, css: '.posts.title'
  button :open, css: '.posts.open-btn'
end
```
define it as
```ruby
class PostsRegion
  include Watirsome::Region
  locator class: 'posts'

  div :title, class: 'title'
  button :open, class: 'open-btn'
end
```

In that case, if we need to redefine locator for a whole region, we address it as last parameter. If we need to redefine existing locator (or add new one) for an element inside the region which included in certain page, we can describe it in block:
```ruby 
class PostsRegion
  include Watirsome::Region
  locator class: 'posts'

  div :title, class: 'title'
  button :open, class: 'open-btn'
end

class Page
  include Watirsome::Page

  region :posts, class: 'landing-posts' do # do we need to explicitly specify PostsRegion as a included region class?
    button :open, class: 'view-btn'
  end
end
```
Just thoughts.

**Comment by tk8817** [comment]
We did a session to come up with some core behaviors & nice to have behaviors. There is a lot of influence from Site-Prism & Dane Anderson's page-section approach. 

### A Region should: 
- provide a namespace for referencing included watir elements 
- utilize a root node for locating included watir elements 
- support pluralism, returning an array of regions
- support sub-region & sub-regions 
- respond to element methods (`.exists?` / `.visible?` / `.click` / `wait_until`)
- have a 'multi-use' form where an outer class can be used

### A Region may: 
- allow the co-relatation of watir elements which do not share a root node
- have a 'single-use' form (block syntax) where no outer class is required
- have a 'mixed-use' form where a class and a block can be combined
- be lazy loaded at time of call rather than page object instantiation 


### Examples 
#### 'multi-use' class specification
```ruby
module Regions
  class Post
    include Watirsome::Region
    div :title, class: 'title'
  end
end

class Page
  include Watirsome::Page
  region :post, Regions::Post, class: 'landing-posts' 
end
```

#### co-relate without shared node
```ruby
module Regions
  class Post
    include Watirsome::Region
    div :title, class: 'title'
    span :title, xpath: '//some/lookup' #element not a child of root, but we want shared namespace
  end
end

class Page
  include Watirsome::Page
  region :post, Regions::Post, class: 'landing-posts' 
end
```

#### respond like an element
```ruby
module Regions
  class Post
    include Watirsome::Region
    div :title, class: 'title'
  end
end

class Page
  include Watirsome::Page
  region :post, Regions::Post, class: 'landing-posts' 
end

page = Page.new(browser)
puts page.post.exists? # returns existence of post region
puts page.post.visible? # returns visibility of post region
puts page.post.click # clicks post region root node
```

#### pluralism (regions)
```ruby
module Regions
  class Items
    include Watirsome::Region
    div :title, class: 'title'
  end
end

class Page
  include Watirsome::Page
  regions :items, Regions::Items, class: 'generic-class-name' 
end

page = Page.new(browser)
puts page.items # returns array of regions
puts page.items[0] # returns first region
puts page.items[1].title # returns title of the second region
```

#### sub-region / sub-regions
```ruby
module Regions
  class Items
    include Watirsome::Region
    div :title, class: 'title'
    regions :reviews, Regions::Reviews, class: 'generic-class-name' 
  end
end

module Regions
  class Reviews
    include Watirsome::Region
    div :stars, class: 'title'
  end
end

class Page
  include Watirsome::Page
  regions :items, Regions::Items, class: 'generic-class-name' 
end

page = Page.new(browser)
puts page.items.reviews # maybe crazy. Return flat map array of all items+reviews regions ? 
puts page.items[0].reviews # return array of reviews for first item
puts page.items[0].reviews[0] # returns first review for first item
puts page.items[0].reviews[0].stars # returns stars text of first review of first item
```

**Comment by p0deje** [comment]
> provide a namespace for referencing included watir elements

:+1:

> utilize a root node for locating included watir elements

👍 (I think it can either defined like in your example, or can be passed to constructor)

> support pluralism, returning an array of regions

hm, that's interesting, I need to think about that

> support sub-region & sub-regions

👍 

> respond to element methods (.exists? / .visible? / .click / wait_until)

Why do you think it makes sense? I believe that region should only provide its own API. What element methods will be looking at (root node, something else)?

have a 'multi-use' form where an outer class can be used
A Region may:

allow the co-relatation of watir elements which do not share a root node
have a 'single-use' form (block syntax) where no outer class is required
have a 'mixed-use' form where a class and a block can be combined
be lazy loaded at time of call rather than page object instantiation

**Comment by tk8817** [comment]
Hey @p0deje 

1. for `mixed-use` form: we saw that in this thread from @nonkor and it looked interesting. We are also unsure if it would be a good idea in practice. Intrigued by the idea of updating a locator or adding a new element during the instantiation of a region (via a block).

2. for `co-relation`, look at the example I gave where it uses an xpath to look up an element inside the region, the goal was to show an element that has a different root than the region, but you want it to be in the same namespace. Can explain more if it is still unclear.

3. for `respond to element methods`, we were thinking there might be a polymorphism design in which a region inherits from a watir-element. Another approach would be having a fully seperate API and delegating unspecified methods back to element to see if it can respond? Ideally we just want to ensure we can 'reason' on a region asking if it exists/visible (using the root locator for the check).

**Comment by p0deje** [comment]
> for mixed-use form: we saw that in this thread from @nonkor and it looked interesting. We are also unsure if it would be a good idea in practice. Intrigued by the idea of updating a locator or adding a new element during the instantiation of a region (via a block).

Oh, that makes sense for small regions. I misunderstood you and thought you mean the case when both class and block are passed.

> for co-relation, look at the example I gave where it uses an xpath to look up an element inside the region, the goal was to show an element that has a different root than the region, but you want it to be in the same namespace. Can explain more if it is still unclear.

I understand now and it works like that by default in Watir, so nothing really needs to be changed. If XPath starts with `//` and not `.//`, then it will work.

> for respond to element methods, we were thinking there might be a polymorphism design in which a region inherits from a watir-element. Another approach would be having a fully seperate API and delegating unspecified methods back to element to see if it can respond? Ideally we just want to ensure we can 'reason' on a region asking if it exists/visible (using the root locator for the check).

I see what you're saying. Still, I feel like we should not mix Element and Region interfaces because they have different responsibilities. They way I see it is that we should do something like:

```ruby
class Region::Post
  include Watirsome

  def posts
    # returns array
  end
end

class HomePage
  region :post
end

page = HomePage.new(browser)
# prefer this
page.post.posts.any?
# over this
page.post.present?
```

**Comment by tk8817** [comment]
My team were talking about regions responding about their visibility / existence last night, and an interesting idea came up about having the region expose its root element so that you could use it.

This would give us access to the full Watir::Element API and when you think about it - this is what we actually want when we talk about sending visibility/existence messages to a region. It is actually the rooted locator that we are trying to interact with, not the region as a concept.

Example 
```ruby
class Region::Post
  include Watirsome
end

class HomePage
  include Watirsome
  region :post, Region::Post, id: 'some_id'
end

page = HomePage.new(browser)
page.post_element.present? # calling `_element` exposes root element of region
OR
page.post.root.present? # calling .root exposes root element of region
```

**Comment by p0deje** [comment]
I actually like last one, though I'd change it to:

```ruby
page.post.element.present?
```

since I assume nobody will want to define `#element` method in region, but `#root` can be redefined.

**Comment by p0deje** [comment]
Support for most of what we discussed here is now in master. The documentation with examples is [here](https://github.com/p0deje/watirsome/blob/84e4f3d3a73943ac967a63e511185eb73d46a31b/lib/watirsome.rb#L173-L304), so I won't cross-post it to this issue.

I'm going to close this for now as most of page-sections features are supported now and we can create separate issues for improvements. Thank you all for this discussion and your ideas!
